# Generated by Django 5.2.4 on 2025-09-13 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TuningJob',
            fields=[
                ('job_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('strategy_spec', models.JSONField()),
                ('param_space', models.JSONField()),
                ('search_type', models.CharField(choices=[('grid', 'Grid'), ('random', 'Random')], max_length=20)),
                ('budget', models.IntegerField(default=10)),
                ('objective', models.CharField(default='sharpe_ratio', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('total_runs', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TuningRun',
            fields=[
                ('run_id', models.AutoField(primary_key=True, serialize=False)),
                ('params', models.JSONField()),
                ('metrics_json', models.JSONField()),
                ('equity_curve_data', models.JSONField()),
                ('trades_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='api.tuningjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
